import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :angen, AngenWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :angen,
  json_schema_path: "/apps/angen/lib/angen-0.0.1/priv/static/schema"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Angen.Finch

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :logger,
  format: "$date $time [$level] $metadata $message\n",
  level: :info

config :logger, :default_formatter,
  format: "$date $time [$level] $metadata $message\n",
  # metadata: [:error_code, :file, :request_id, :user_id]
  metadata: [:error_code, :request_id, :user_id]

config :logger, :default_handler,
  config: [
    file: ~c"/var/log/angen/info.log",
    filesync_repeat_interval: 5000,
    file_check: 5000,
    max_no_bytes: 10_000_000,
    max_no_files: 5,
    compress_on_rotate: true
  ]

# config :logger, :error_log,
#   path: "/var/log/angen/error.log",
#   format: "$date $time [$level] $metadata $message\n",
#   # metadata: [:request_id, :user_id],
#   level: :error

# config :logger, :info_log,
#   path: "/var/log/angen/info.log",
#   format: "$date $time [$level] $metadata $message\n",
#   # metadata: [:request_id, :user_id],
#   level: :info
